In [1]:
import fitz

In [2]:
doc = fitz.open('../data/tata-motor.pdf')

print(f"The document has {doc.page_count} pages.")

The document has 590 pages.

# Finding the Headings: Just detect patterns, assign meaning, and build heirarchy

In [3]:
all_spans = []
for page_num,page in enumerate(doc):
    blocks = page.get_text("dict")["blocks"]

    for b in blocks:
        if "lines" not in b:
            continue
        for line in b["lines"]:
            for span in line["spans"]:
                text = span["text"].strip()

                if not text:
                    continue

                all_spans.append({
                    "text":text,
                    "size": span["size"],
                    "font": span["font"],
                    "flags": span["flags"],
                    "page": page_num,
                    "y": span["bbox"][1]
                })

## Understanding the docs statistically

In [4]:
sizes = [s["size"] for s in all_spans]

avg_size = sum(sizes) / len(sizes)
max_size = max(sizes)
min_size = min(sizes)

print(avg_size,max_size,min_size)

8.713787477229904 75.0 4.647579669952393

In [5]:
heading_thresh = 0.75
subheading_thresh = 1.2

In [6]:
## Heading are often bold
def is_bold(flags):
    return flags & 2 != 0

In [7]:
def classify(span, avg_size, max_size, heading_thresh=0.75,subheading_thresh=1.2):
    text = span["text"]
    size = span["size"]
    bold = is_bold(span["flags"])

    ## Ignore noisy tiny text
    if len(text) < 2:
        return "ignore"
    
    ## Main Heading
    if size > max_size*heading_thresh and bold:
        return "h1"
    
    ## Subheading
    elif size > avg_size * subheading_thresh:
        return "h2"
    
    # Body   
    else:
        return "body"

In [8]:
structure = []

current_h1 = None
current_h2 = None
i=0
for span in all_spans:
    if(i == 5):
        break
    label = classify(span, avg_size, max_size)
    text = span["text"]
    print(f"The text is : {text}, and it's label is {label}, and all details are {span}")
    i = i+1

The text is : 80, and it's label is h2, and all details are {'text': '80', 'size': 11.0, 'font': 'Calibri-Bold', 'flags': 16, 'page': 0, 'y': 89.02040100097656}
The text is : TH, and it's label is body, and all details are {'text': 'TH', 'size': 6.413000106811523, 'font': 'Calibri-Bold', 'flags': 17, 'page': 0, 'y': 90.12308502197266}
The text is : INTEGRATED ANNUAL, and it's label is h2, and all details are {'text': 'INTEGRATED ANNUAL', 'size': 11.0, 'font': 'Calibri-Bold', 'flags': 16, 'page': 0, 'y': 89.02040100097656}
The text is : REPORT 2024-25, and it's label is h2, and all details are {'text': 'REPORT 2024-25', 'size': 11.0, 'font': 'Calibri-Bold', 'flags': 16, 'page': 0, 'y': 101.02137756347656}
The text is : In a free enterprise, the community is not just, and it's label is h2, and all details are {'text': 'In a free enterprise, the community is not just', 'size': 15.0, 'font': 'Calibri-Bold', 'flags': 16, 'page': 1, 'y': 607.6649780273438}

In [9]:
structure

[]

## We should not have started with Span, this is very small, Let's try with line level

In [10]:
def build_lines(blocks, page_num):
    lines_out = []

    for b in blocks:
        if "lines" not in b:
            continue

        for line in b["lines"]:
            spans = line["spans"]

            text = " ".join([s["text"].strip() for s in spans if s["text"].strip()])

            if not text:
                continue

            font_sizes = [s["size"] for s in spans]
            avg_size = sum(font_sizes) / len(font_sizes)

            is_bold = any((s["flags"] & 2) != 0 for s in spans)

            lines_out.append({
                "text":text,
                "size": avg_size,
                "is_bold":is_bold,
                "page": page_num,
                "bbox": line["bbox"]
            })      
    return lines_out

#### Use percentile instead of hardcoded values for threshold

In [11]:
import numpy as np

all_lines = []
for page_num,page in enumerate(doc):
    blocks = page.get_text("dict")["blocks"]
    all_lines.extend(build_lines(blocks,page_num))


sizes = [l["size"] for l in all_lines]

p90 = np.percentile(sizes,90)
p75 = np.percentile(sizes,75)
p50 = np.percentile(sizes,50)

In [12]:
def is_noise(text):
    if len(text) < 3:
        return True
    
    if text.isdigit():
        return True
    
    if len(text.split()) == 1 and len(text) < 4:
        return True
    
    return False

In [13]:
def classify_lines(line, p90,p75):
    text = line["text"]

    if len(text) < 3:
        return "ignore"
    
    ## Header
    if line["size"] >= p90 and line["is_bold"]:
        return "h1"
    
    ## Sub
    elif line["size"] >= p75:
        return "h2"
    
    else:
        return "body"

In [14]:
current_h1 = None
current_h2 = None
i=0
for line in all_lines:
    if(i == 5):
        break

    if(is_noise(line["text"])):
        continue
    
    label = classify_lines(line, p90, p75)
    text = line["text"]
    print(f"The text is : {text}, and it's label is {label}, and all details are {line}")
    i = i+1

The text is : 80 TH INTEGRATED ANNUAL, and it's label is body, and all details are {'text': '80 TH INTEGRATED ANNUAL', 'size': 9.471000035603842, 'is_bold': False, 'page': 0, 'bbox': (49.827701568603516, 89.02040100097656, 172.60302734375, 104.28839874267578)}
The text is : REPORT 2024-25, and it's label is h2, and all details are {'text': 'REPORT 2024-25', 'size': 11.0, 'is_bold': False, 'page': 0, 'bbox': (49.82870101928711, 101.02137756347656, 125.52302551269531, 116.28937530517578)}
The text is : In a free enterprise, the community is not just, and it's label is h2, and all details are {'text': 'In a free enterprise, the community is not just', 'size': 15.0, 'is_bold': False, 'page': 1, 'bbox': (155.38999938964844, 607.6649780273438, 443.2835998535156, 628.4849853515625)}
The text is : another stakeholder in business, but is in fact, and it's label is h2, and all details are {'text': 'another stakeholder in business, but is in fact', 'size': 15.0, 'is_bold': False, 'page': 1, 'bbox': (156.78599548339844, 625.6649780273438, 441.8894348144531, 646.4849853515625)}
The text is : the very purpose of its existence., and it's label is h2, and all details are {'text': 'the very purpose of its\xa0existence.', 'size': 15.0, 'is_bold': False, 'page': 1, 'bbox': (194.72799682617188, 643.6649780273438, 400.54302978515625, 664.4849853515625)}

In [15]:
import pandas as pd

df = pd.DataFrame(all_lines)
df["label"] = df.apply(lambda x: classify_lines(x,p90, p75), axis=1)

df.to_csv("lines_debug.csv", index=False)

In [16]:
df.head()

,text,size,is_bold,page,bbox,label
0,80 TH INTEGRATED ANNUAL,9.471,False,0,"(49.827701568603516, 89.02040100097656, 172.60...",body
1,REPORT 2024-25,11.000,False,0,"(49.82870101928711, 101.02137756347656, 125.52...",h2
2,"In a free enterprise, the community is not just",15.000,False,1,"(155.38999938964844, 607.6649780273438, 443.28...",h2
3,"another stakeholder in business, but is in fact",15.000,False,1,"(156.78599548339844, 625.6649780273438, 441.88...",h2
4,the very purpose of its existence.,15.000,False,1,"(194.72799682617188, 643.6649780273438, 400.54...",h2

## Observation: I think that first few pages are just noise for my dataset. Let's try removing it, and then again try making df again

In [17]:
import numpy as np

all_lines = []
for page_num,page in enumerate(doc):

    ## Let's remove page number < 2
    if page_num < 2:
        continue
    blocks = page.get_text("dict")["blocks"]
    all_lines.extend(build_lines(blocks,page_num))


sizes = [l["size"] for l in all_lines]

p90 = np.percentile(sizes,90)
p75 = np.percentile(sizes,75)
p50 = np.percentile(sizes,50)

In [18]:
i=0
for line in all_lines:
    if(i == 5):
        break

    if(is_noise(line["text"])):
        continue
    
    label = classify_lines(line, p90, p75)
    text = line["text"]
    print(f"The text is : {text}, and it's label is {label}, and all details are {line}")
    i = i+1

The text is : In Remembrance, and it's label is h2, and all details are {'text': 'In Remembrance', 'size': 18.0, 'is_bold': False, 'page': 2, 'bbox': (235.58900451660156, 86.29800415039062, 363.75262451171875, 111.28199768066406)}
The text is : 28.12.1937 – 09.10.2024, and it's label is h2, and all details are {'text': '28.12.1937 – 09.10.2024', 'size': 12.5, 'is_bold': False, 'page': 2, 'bbox': (240.5919952392578, 500.17498779296875, 354.6722412109375, 516.9000244140625)}
The text is : Padma Vibhushan, and it's label is h2, and all details are {'text': 'Padma Vibhushan', 'size': 18.0, 'is_bold': False, 'page': 2, 'bbox': (231.77000427246094, 455.2980041503906, 363.50653076171875, 480.2820129394531)}
The text is : Ratan N Tata, and it's label is h2, and all details are {'text': 'Ratan N Tata', 'size': 20.0, 'is_bold': False, 'page': 2, 'bbox': (245.86599731445312, 474.2200012207031, 349.4200134277344, 501.9800109863281)}
The text is : It is with a profound sense of loss that we bid farewell to Mr. Ratan Naval Tata,, and it's label is h2, and all details are {'text': 'It is with a profound sense of loss that we bid farewell to Mr. Ratan Naval Tata,', 'size': 11.0, 'is_bold': False, 'page': 2, 'bbox': (124.84500122070312, 540.7139892578125, 472.86956787109375, 555.4320068359375)}

In [19]:
import pandas as pd

df_2 = pd.DataFrame(all_lines)
df_2["label"] = df_2.apply(lambda x: classify_lines(x,p90, p75), axis=1)

df_2.to_csv("lines_debug.csv", index=False)

In [20]:
df_2.head(10)

,text,size,is_bold,page,bbox,label
0,In Remembrance,18.0,False,2,"(235.58900451660156, 86.29800415039062, 363.75...",h2
1,28.12.1937 – 09.10.2024,12.5,False,2,"(240.5919952392578, 500.17498779296875, 354.67...",h2
2,Padma Vibhushan,18.0,False,2,"(231.77000427246094, 455.2980041503906, 363.50...",h2
3,Ratan N Tata,20.0,False,2,"(245.86599731445312, 474.2200012207031, 349.42...",h2
4,It is with a profound sense of loss that we bi...,11.0,False,2,"(124.84500122070312, 540.7139892578125, 472.86...",h2
5,a truly uncommon leader whose immeasurable con...,11.0,False,2,"(125.14099884033203, 555.7139892578125, 472.61...",h2
6,only the Tata Group but also the very fabric o...,11.0,False,2,"(170.67300415039062, 570.7139892578125, 424.60...",h2
7,"For the Tata Group, Mr. Tata was more than a c...",11.0,False,2,"(136.0989990234375, 597.7139892578125, 461.639...",h2
8,example. With an unwavering commitment to exce...,11.0,False,2,"(141.36300659179688, 612.7139892578125, 456.38...",h2
9,"innovation, the Tata Group under his stewardsh...",11.0,False,2,"(123.62999725341797, 627.7139892578125, 474.13...",h2

## Let's see the labels, and try understanding about why it is happening like that

In [21]:
df_2["label"].value_counts()

label
body      35004
h2        23990
ignore     9279
h1          227
Name: count, dtype: int64

In [22]:
# for h1(most important)
df_2[df_2["label"] == 'h1']

,text,size,is_bold,page,bbox,label
39,Sales (wholesale excl. CJLR),11.0,True,4,"(51.02360153198242, 231.5299835205078, 157.664...",h1
40,units,9.5,True,4,"(51.02360153198242, 251.2530059814453, 69.8326...",h1
43,I crore,9.5,True,4,"(221.43299865722656, 251.2530059814453, 247.87...",h1
46,I crore,9.5,True,4,"(220.93899536132812, 437.25299072265625, 247.3...",h1
62,$ billion*,9.5,True,4,"(51.02360153198242, 437.25299072265625, 85.599...",h1
...,...,...,...,...,...,...
63537,"the Company for a period of five years, i.e. ,...",9.5,True,540,"(306.6344909667969, 323.2514953613281, 546.401...",h1
63558,Mr Chowdary has given his declaration to the B...,9.5,True,540,"(306.63446044921875, 593.2321166992188, 546.39...",h1
63559,"alia , confirming that (i) he meets the criter...",9.5,True,540,"(306.6344909667969, 605.2305908203125, 546.397...",h1
63749,"Regulations, 2015 (‘SEBI Listing Regulations’)...",9.5,True,542,"(306.63800048828125, 311.25494384765625, 546.3...",h1
68486,(formerly known as Link Intime India Private L...,13.0,True,587,"(245.43800354003906, 634.6712646484375, 521.59...",h1

## Observation: Boldness can't be a good feature for header, let's start with working on with word count + size factor

In [23]:
def word_count(text):
    return len(text.split())

def is_sentence(text):
    return word_count(text) > 8

def is_title_like(text):
    return text.isupper() or text.istitle()

In [24]:
def classify_lines(line, p90, p75):
    text = line["text"]
    wc = word_count(text)
    size = line['size']
    
    if is_noise(text):
        return "ignore"
    
    if wc > 8:
        return "body"
    
    ## Header
    if size >= p90 and wc<= 6:
        return "h1"
    
    # Sub header
    if size >= p75 and wc <= 8:
        return "h2"

    return "body"

In [25]:
import numpy as np

all_lines = []
for page_num,page in enumerate(doc):

    ## Let's remove page number < 2
    if page_num < 2:
        continue
    blocks = page.get_text("dict")["blocks"]
    all_lines.extend(build_lines(blocks,page_num))


sizes = [l["size"] for l in all_lines]

p90 = np.percentile(sizes,90)
p75 = np.percentile(sizes,75)
p50 = np.percentile(sizes,50)

i=0
for line in all_lines:
    if(i == 5):
        break

    if(is_noise(line["text"])):
        continue
    
    label = classify_lines(line, p90, p75)
    text = line["text"]
    print(f"The text is : {text}, and it's label is {label}, and all details are {line}")
    i = i+1

The text is : In Remembrance, and it's label is h1, and all details are {'text': 'In Remembrance', 'size': 18.0, 'is_bold': False, 'page': 2, 'bbox': (235.58900451660156, 86.29800415039062, 363.75262451171875, 111.28199768066406)}
The text is : 28.12.1937 – 09.10.2024, and it's label is h1, and all details are {'text': '28.12.1937 – 09.10.2024', 'size': 12.5, 'is_bold': False, 'page': 2, 'bbox': (240.5919952392578, 500.17498779296875, 354.6722412109375, 516.9000244140625)}
The text is : Padma Vibhushan, and it's label is h1, and all details are {'text': 'Padma Vibhushan', 'size': 18.0, 'is_bold': False, 'page': 2, 'bbox': (231.77000427246094, 455.2980041503906, 363.50653076171875, 480.2820129394531)}
The text is : Ratan N Tata, and it's label is h1, and all details are {'text': 'Ratan N Tata', 'size': 20.0, 'is_bold': False, 'page': 2, 'bbox': (245.86599731445312, 474.2200012207031, 349.4200134277344, 501.9800109863281)}
The text is : It is with a profound sense of loss that we bid farewell to Mr. Ratan Naval Tata,, and it's label is body, and all details are {'text': 'It is with a profound sense of loss that we bid farewell to Mr. Ratan Naval Tata,', 'size': 11.0, 'is_bold': False, 'page': 2, 'bbox': (124.84500122070312, 540.7139892578125, 472.86956787109375, 555.4320068359375)}

In [27]:
import pandas as pd

df_3 = pd.DataFrame(all_lines)
df_3["label"] = df_3.apply(lambda x: classify_lines(x,p90, p75), axis=1)

df_3.to_csv("lines_debug.csv", index=False)

df_3.head(10)

,text,size,is_bold,page,bbox,label
0,In Remembrance,18.0,False,2,"(235.58900451660156, 86.29800415039062, 363.75...",h1
1,28.12.1937 – 09.10.2024,12.5,False,2,"(240.5919952392578, 500.17498779296875, 354.67...",h1
2,Padma Vibhushan,18.0,False,2,"(231.77000427246094, 455.2980041503906, 363.50...",h1
3,Ratan N Tata,20.0,False,2,"(245.86599731445312, 474.2200012207031, 349.42...",h1
4,It is with a profound sense of loss that we bi...,11.0,False,2,"(124.84500122070312, 540.7139892578125, 472.86...",body
5,a truly uncommon leader whose immeasurable con...,11.0,False,2,"(125.14099884033203, 555.7139892578125, 472.61...",body
6,only the Tata Group but also the very fabric o...,11.0,False,2,"(170.67300415039062, 570.7139892578125, 424.60...",body
7,"For the Tata Group, Mr. Tata was more than a c...",11.0,False,2,"(136.0989990234375, 597.7139892578125, 461.639...",body
8,example. With an unwavering commitment to exce...,11.0,False,2,"(141.36300659179688, 612.7139892578125, 456.38...",body
9,"innovation, the Tata Group under his stewardsh...",11.0,False,2,"(123.62999725341797, 627.7139892578125, 474.13...",body

In [ ]:
df_3[(df_3["label"] == 'h1') & (df_3["page"] == 255)] ## To analyze a single page

,text,size,is_bold,page,bbox,label
23230,Management Discussion and Analysis,21.0,False,255,"(51.02360153198242, 70.18099975585938, 375.620...",h1
23231,"Provident Fund Organization (“EPFO”), offered to",9.5,False,255,"(70.8666000366211, 110.25299835205078, 290.775...",h1
23236,fund exemption.,9.5,False,255,"(70.8666000366211, 170.24537658691406, 135.252...",h1
23275,agreed in the minutes.,9.5,False,255,"(70.8666000366211, 656.1987915039062, 158.5079...",h1
23276,Tax expenses / (credit):,10.0,False,255,"(70.86360168457031, 679.6099853515625, 167.722...",h1
23286,following reasons:,9.5,False,255,"(326.485595703125, 164.2409210205078, 397.2975...",h1
23290,"unabsorbed depreciation ₹763 crores, resulting in",9.5,False,255,"(346.3310852050781, 206.24037170410156, 546.40...",h1
23297,"During FY25, Jaguar Land Rover recognized",9.5,False,255,"(346.340576171875, 284.2352294921875, 546.4171...",h1
23300,previously unrecognized unused business losses.,9.5,False,255,"(346.340576171875, 320.2306823730469, 535.3931...",h1
23303,"of joint venture, joint operation, associates",9.5,False,255,"(346.3500671386719, 350.231689453125, 546.4246...",h1
23306,increased profitability.,9.5,False,255,"(346.35009765625, 386.2272033691406, 434.05697...",h1
23307,Share of profit/(loss) of equity-accounted inv...,10.0,False,255,"(326.4779968261719, 409.6099853515625, 544.249...",h1
23315,"business, leading to higher profits.",9.5,False,255,"(326.4834899902344, 509.24249267578125, 460.32...",h1
23316,Non-controlling interests in consolidated subs...,9.5,False,255,"(326.4834899902344, 527.12158203125, 546.40173...",h1
23317,net of tax:,9.5,False,255,"(326.4834899902344, 539.1200561523438, 367.456...",h1
23325,Profit after tax:,10.0,False,255,"(326.4779968261719, 652.6099853515625, 390.399...",h1
23329,the following factors:,9.5,False,255,"(326.4834899902344, 704.24853515625, 409.52963...",h1
23331,Earnings,9.5,False,255,"(346.3289794921875, 722.2510375976562, 381.653...",h1
23332,before,9.5,False,255,"(391.76654052734375, 722.2510375976562, 419.86...",h1
23333,other,9.5,False,255,"(429.97357177734375, 722.2510375976562, 453.47...",h1
23334,income,9.5,False,255,"(463.5835876464844, 722.2510375976562, 494.519...",h1
23335,(excluding,9.5,False,255,"(504.62646484375, 722.2510375976562, 546.40734...",h1
23336,"Incentives), finance cost, foreign exchange gain/",9.5,False,255,"(346.3289794921875, 734.24951171875, 544.25170...",h1

### Observation: Since body size is dominating, and others are outlier, therefore percentile approach is failing 90 percentile is also too low. And it will be a common pattern of body size dominating in almost all financial reports. 

### Hypothesis 1: Instead of percentile, if we mind the mode size, we can get the body size, then we can use a threshold to add, and we can get our headings.

In [37]:
from collections import Counter

size_counts = Counter(round(l['size'], 1) for l in all_lines)
body_size = size_counts.most_common(1)[0][0]

print("Body size:", body_size)

Body size: 8.5

In [38]:
## Can change these values
h2_threshold = body_size + 2.0
h1_threshold = body_size + 4.0

In [50]:
def classify_lines(line, body_size):
    text = line["text"]
    wc = len(text.split())
    size = line["size"]
    
    if is_noise(text):
        return "ignore"
    
    if wc > 8:
        return "body"
    
    if size >= body_size + 4 and wc <= 7:
        return 'h1'
    
    if size >= body_size + 2 and wc <= 9:
        return 'h2'
    
    return "body"

In [51]:
import numpy as np

all_lines = []
for page_num,page in enumerate(doc):

    ## Let's remove page number < 2
    if page_num < 2:
        continue
    blocks = page.get_text("dict")["blocks"]
    all_lines.extend(build_lines(blocks,page_num))

i=0
for line in all_lines:
    if(i == 5):
        break

    if(is_noise(line["text"])):
        continue
    
    label = classify_lines(line, body_size)
    text = line["text"]
    print(f"The text is : {text}, and it's label is {label}, and all details are {line}")
    i = i+1

The text is : In Remembrance, and it's label is h1, and all details are {'text': 'In Remembrance', 'size': 18.0, 'is_bold': False, 'page': 2, 'bbox': (235.58900451660156, 86.29800415039062, 363.75262451171875, 111.28199768066406)}
The text is : 28.12.1937 – 09.10.2024, and it's label is h1, and all details are {'text': '28.12.1937 – 09.10.2024', 'size': 12.5, 'is_bold': False, 'page': 2, 'bbox': (240.5919952392578, 500.17498779296875, 354.6722412109375, 516.9000244140625)}
The text is : Padma Vibhushan, and it's label is h1, and all details are {'text': 'Padma Vibhushan', 'size': 18.0, 'is_bold': False, 'page': 2, 'bbox': (231.77000427246094, 455.2980041503906, 363.50653076171875, 480.2820129394531)}
The text is : Ratan N Tata, and it's label is h1, and all details are {'text': 'Ratan N Tata', 'size': 20.0, 'is_bold': False, 'page': 2, 'bbox': (245.86599731445312, 474.2200012207031, 349.4200134277344, 501.9800109863281)}
The text is : It is with a profound sense of loss that we bid farewell to Mr. Ratan Naval Tata,, and it's label is body, and all details are {'text': 'It is with a profound sense of loss that we bid farewell to Mr. Ratan Naval Tata,', 'size': 11.0, 'is_bold': False, 'page': 2, 'bbox': (124.84500122070312, 540.7139892578125, 472.86956787109375, 555.4320068359375)}

In [52]:
import pandas as pd

df_4 = pd.DataFrame(all_lines)
df_4["label"] = df_4.apply(lambda x: classify_lines(x,body_size), axis=1)

df_4.to_csv("lines_debug.csv", index=False)

df_4.head(10)

,text,size,is_bold,page,bbox,label
0,In Remembrance,18.0,False,2,"(235.58900451660156, 86.29800415039062, 363.75...",h1
1,28.12.1937 – 09.10.2024,12.5,False,2,"(240.5919952392578, 500.17498779296875, 354.67...",h1
2,Padma Vibhushan,18.0,False,2,"(231.77000427246094, 455.2980041503906, 363.50...",h1
3,Ratan N Tata,20.0,False,2,"(245.86599731445312, 474.2200012207031, 349.42...",h1
4,It is with a profound sense of loss that we bi...,11.0,False,2,"(124.84500122070312, 540.7139892578125, 472.86...",body
5,a truly uncommon leader whose immeasurable con...,11.0,False,2,"(125.14099884033203, 555.7139892578125, 472.61...",body
6,only the Tata Group but also the very fabric o...,11.0,False,2,"(170.67300415039062, 570.7139892578125, 424.60...",body
7,"For the Tata Group, Mr. Tata was more than a c...",11.0,False,2,"(136.0989990234375, 597.7139892578125, 461.639...",body
8,example. With an unwavering commitment to exce...,11.0,False,2,"(141.36300659179688, 612.7139892578125, 456.38...",body
9,"innovation, the Tata Group under his stewardsh...",11.0,False,2,"(123.62999725341797, 627.7139892578125, 474.13...",body

In [ ]:
df_4[(df_4["label"] == 'ignore') & (df_4["page"] == 317)]

text  size      is_bold  page  bbox                                                                           label
(1)   6.260991  False    317   (338.7502746582031, 73.4930191040039, 348.11627197265625, 79.72576904296875)   ignore    1
-     6.260991  False    317   (372.749267578125, 465.9295959472656, 382.1152648925781, 467.6431884765625)    ignore    1
                               (365.6512756347656, 539.6312866210938, 375.01727294921875, 541.3449096679688)  ignore    1
                               (365.6512756347656, 574.5921020507812, 375.01727294921875, 576.3057250976562)  ignore    1
                               (365.6512756347656, 608.8585205078125, 375.01727294921875, 610.5721435546875)  ignore    1
                                                                                                                       ..
                               (294.21630859375, 438.54034423828125, 303.5823059082031, 440.2539367675781)    ignore    1
                               (294.21630859375, 465.8963317871094, 303.5823059082031, 467.60992431640625)    ignore    1
                               (294.21630859375, 504.6371154785156, 303.5823059082031, 506.3507080078125)     ignore    1
                               (294.21630859375, 539.597900390625, 303.5823059082031, 541.3115234375)         ignore    1
99    6.260991  False    317   (338.7502746582031, 640.8345336914062, 348.11627197265625, 646.512939453125)   ignore    1
Name: count, Length: 255, dtype: int64

## Observations: 

* H1 can be very big in word count. Word count should not be the limit like this one "Consolidated Statement of Changes in Equity for the year ended March 31, 2025
"
* H1 doesn't generally endswith .,;,,

In [61]:
def classify_lines(line, body_size):
    text = line["text"].strip()
    wc = len(text.split())
    size = line["size"]

    if is_noise(text):
        return "ignore"
    
    if text.endswith(('.',";",',')):
        return "body"
    
    # h1
    if size >= body_size + 4 :
        return "h1"
    
    if size >= body_size + 2 and wc <= 8:
        return "h2"
    
    if wc > 10:
        return "body"
    
    return "body"

In [62]:
import numpy as np

all_lines = []
for page_num,page in enumerate(doc):

    ## Let's remove page number < 2
    if page_num < 2:
        continue
    blocks = page.get_text("dict")["blocks"]
    all_lines.extend(build_lines(blocks,page_num))

i=0
for line in all_lines:
    if(i == 5):
        break

    if(is_noise(line["text"])):
        continue
    
    label = classify_lines(line, body_size)
    text = line["text"]
    print(f"The text is : {text}, and it's label is {label}, and all details are {line}")
    i = i+1

The text is : In Remembrance, and it's label is h1, and all details are {'text': 'In Remembrance', 'size': 18.0, 'is_bold': False, 'page': 2, 'bbox': (235.58900451660156, 86.29800415039062, 363.75262451171875, 111.28199768066406)}
The text is : 28.12.1937 – 09.10.2024, and it's label is h1, and all details are {'text': '28.12.1937 – 09.10.2024', 'size': 12.5, 'is_bold': False, 'page': 2, 'bbox': (240.5919952392578, 500.17498779296875, 354.6722412109375, 516.9000244140625)}
The text is : Padma Vibhushan, and it's label is h1, and all details are {'text': 'Padma Vibhushan', 'size': 18.0, 'is_bold': False, 'page': 2, 'bbox': (231.77000427246094, 455.2980041503906, 363.50653076171875, 480.2820129394531)}
The text is : Ratan N Tata, and it's label is h1, and all details are {'text': 'Ratan N Tata', 'size': 20.0, 'is_bold': False, 'page': 2, 'bbox': (245.86599731445312, 474.2200012207031, 349.4200134277344, 501.9800109863281)}
The text is : It is with a profound sense of loss that we bid farewell to Mr. Ratan Naval Tata,, and it's label is body, and all details are {'text': 'It is with a profound sense of loss that we bid farewell to Mr. Ratan Naval Tata,', 'size': 11.0, 'is_bold': False, 'page': 2, 'bbox': (124.84500122070312, 540.7139892578125, 472.86956787109375, 555.4320068359375)}

In [63]:
import pandas as pd

df_5 = pd.DataFrame(all_lines)
df_5["label"] = df_5.apply(lambda x: classify_lines(x,body_size), axis=1)

df_5.to_csv("lines_debug.csv", index=False)

df_5.head(10)

,text,size,is_bold,page,bbox,label
0,In Remembrance,18.0,False,2,"(235.58900451660156, 86.29800415039062, 363.75...",h1
1,28.12.1937 – 09.10.2024,12.5,False,2,"(240.5919952392578, 500.17498779296875, 354.67...",h1
2,Padma Vibhushan,18.0,False,2,"(231.77000427246094, 455.2980041503906, 363.50...",h1
3,Ratan N Tata,20.0,False,2,"(245.86599731445312, 474.2200012207031, 349.42...",h1
4,It is with a profound sense of loss that we bi...,11.0,False,2,"(124.84500122070312, 540.7139892578125, 472.86...",body
5,a truly uncommon leader whose immeasurable con...,11.0,False,2,"(125.14099884033203, 555.7139892578125, 472.61...",body
6,only the Tata Group but also the very fabric o...,11.0,False,2,"(170.67300415039062, 570.7139892578125, 424.60...",body
7,"For the Tata Group, Mr. Tata was more than a c...",11.0,False,2,"(136.0989990234375, 597.7139892578125, 461.639...",body
8,example. With an unwavering commitment to exce...,11.0,False,2,"(141.36300659179688, 612.7139892578125, 456.38...",body
9,"innovation, the Tata Group under his stewardsh...",11.0,False,2,"(123.62999725341797, 627.7139892578125, 474.13...",body

In [68]:
df_5[(df_5["label"] == 'body') & (df_5["page"] == 254)] ## To analyze a single page

,text,size,is_bold,page,bbox,label
23075,CONSOLIDATED,8.0,False,254,"(334.8330078125, 788.9246215820312, 387.185028...",body
23076,FINANCIALS,8.0,False,254,"(334.8330078125, 798.5245971679688, 373.432952...",body
23078,STANDALONE,8.0,False,254,"(425.625, 788.9246215820312, 471.1097412109375...",body
23079,FINANCIALS,8.0,False,254,"(425.625, 798.5245971679688, 464.2249450683594...",body
23082,STATUTORY,8.0,False,254,"(243.04200744628906, 788.9371337890625, 281.87...",body
...,...,...,...,...,...,...
23220,(12),8.5,False,254,"(525.2754516601562, 683.14599609375, 539.04547...",body
23221,Total,8.5,False,254,"(330.48095703125, 696.4315185546875, 348.46359...",body
23224,FY25,9.5,False,254,"(326.4835205078125, 716.1295166015625, 345.811...",body
23225,Tata Motors Limited (the “Company”) in October...,9.5,False,254,"(326.4834899902344, 734.2554931640625, 546.395...",body
23226,"had by way of an application, addressed to the...",9.5,False,254,"(326.4834899902344, 746.2540283203125, 546.398...",body

In [69]:
import pandas as pd

# mask for numeric values in 'text'
numeric_mask = pd.to_numeric(df_5['text'], errors='coerce').notna()

# mask for label == ignore
ignore_mask = df_5['label'] == 'ignore'

# count 1: both conditions
valid_count = df_5[numeric_mask & ignore_mask].shape[0]

# count 2: total ignore labels
total_ignore = df_5[ignore_mask].shape[0]

# percentage
percentage = (valid_count / total_ignore) * 100 if total_ignore > 0 else 0

print(valid_count, total_ignore, percentage)

7382 14986 49.2593086881089

## Observation: Around 50% of 'ignore' label is numerical, they definately have came from table

7382

## Now let's try making table LLM understandable

## The tables will be having numeric heavy lines

In [75]:
import re

def numeric_ratio(text):
    tokens = text.split()
    if not tokens:
        return 0
    
    numeric_tokens = sum(1 for t in tokens if re.search(r'\d',t))
    return numeric_tokens / len(tokens)

def is_table_line(text):
    return numeric_ratio(text) > 0.4

In [76]:
def classify_extended(line,body_size):
    base_label = classify_lines(line,body_size)
    text = line["text"]

    if base_label == "ignore":
        if is_table_line(text):
            return "table"
        return "ignore"
    
    if base_label == "body":
        if is_table_line(text):
            return "table"
        
    return base_label

In [77]:
import numpy as np

all_lines = []
for page_num,page in enumerate(doc):

    ## Let's remove page number < 2
    if page_num < 2:
        continue
    blocks = page.get_text("dict")["blocks"]
    all_lines.extend(build_lines(blocks,page_num))

i=0
for line in all_lines:
    if(i == 5):
        break

    if(is_noise(line["text"])):
        continue
    
    label = classify_extended(line, body_size)
    text = line["text"]
    print(f"The text is : {text}, and it's label is {label}, and all details are {line}")
    i = i+1

The text is : In Remembrance, and it's label is h1, and all details are {'text': 'In Remembrance', 'size': 18.0, 'is_bold': False, 'page': 2, 'bbox': (235.58900451660156, 86.29800415039062, 363.75262451171875, 111.28199768066406)}
The text is : 28.12.1937 – 09.10.2024, and it's label is h1, and all details are {'text': '28.12.1937 – 09.10.2024', 'size': 12.5, 'is_bold': False, 'page': 2, 'bbox': (240.5919952392578, 500.17498779296875, 354.6722412109375, 516.9000244140625)}
The text is : Padma Vibhushan, and it's label is h1, and all details are {'text': 'Padma Vibhushan', 'size': 18.0, 'is_bold': False, 'page': 2, 'bbox': (231.77000427246094, 455.2980041503906, 363.50653076171875, 480.2820129394531)}
The text is : Ratan N Tata, and it's label is h1, and all details are {'text': 'Ratan N Tata', 'size': 20.0, 'is_bold': False, 'page': 2, 'bbox': (245.86599731445312, 474.2200012207031, 349.4200134277344, 501.9800109863281)}
The text is : It is with a profound sense of loss that we bid farewell to Mr. Ratan Naval Tata,, and it's label is body, and all details are {'text': 'It is with a profound sense of loss that we bid farewell to Mr. Ratan Naval Tata,', 'size': 11.0, 'is_bold': False, 'page': 2, 'bbox': (124.84500122070312, 540.7139892578125, 472.86956787109375, 555.4320068359375)}

In [78]:
import pandas as pd

df_6 = pd.DataFrame(all_lines)
df_6["label"] = df_6.apply(lambda x: classify_extended(x,body_size), axis=1)

df_6.to_csv("lines_debug.csv", index=False)

df_6.head(10)

,text,size,is_bold,page,bbox,label
0,In Remembrance,18.0,False,2,"(235.58900451660156, 86.29800415039062, 363.75...",h1
1,28.12.1937 – 09.10.2024,12.5,False,2,"(240.5919952392578, 500.17498779296875, 354.67...",h1
2,Padma Vibhushan,18.0,False,2,"(231.77000427246094, 455.2980041503906, 363.50...",h1
3,Ratan N Tata,20.0,False,2,"(245.86599731445312, 474.2200012207031, 349.42...",h1
4,It is with a profound sense of loss that we bi...,11.0,False,2,"(124.84500122070312, 540.7139892578125, 472.86...",body
5,a truly uncommon leader whose immeasurable con...,11.0,False,2,"(125.14099884033203, 555.7139892578125, 472.61...",body
6,only the Tata Group but also the very fabric o...,11.0,False,2,"(170.67300415039062, 570.7139892578125, 424.60...",body
7,"For the Tata Group, Mr. Tata was more than a c...",11.0,False,2,"(136.0989990234375, 597.7139892578125, 461.639...",body
8,example. With an unwavering commitment to exce...,11.0,False,2,"(141.36300659179688, 612.7139892578125, 456.38...",body
9,"innovation, the Tata Group under his stewardsh...",11.0,False,2,"(123.62999725341797, 627.7139892578125, 474.13...",body

In [81]:
df_6[(df_6["label"] == 'table') & (df_6["page"] == 231)]

,text,size,is_bold,page,bbox,label
20358,2024-25,8.000,False,231,"(61.64540100097656, 799.6331176757812, 89.9349...",table
20359,228,7.500,False,231,"(519.97900390625, 793.3052368164062, 531.57476...",table
20364,18.5,8.500,False,231,"(418.1895751953125, 123.27899932861328, 433.61...",table
20366,2.4,8.500,False,231,"(420.4930725097656, 135.281005859375, 431.3212...",table
20368,11.5,8.500,False,231,"(418.3000793457031, 147.28302001953125, 433.51...",table
20370,6.1,8.500,False,231,"(420.5440673828125, 159.2850341796875, 431.272...",table
20372,16,8.500,False,231,"(421.6405944824219, 171.28704833984375, 430.17...",table
20374,1,8.500,False,231,"(423.7485656738281, 183.2890625, 428.058074951...",table
20376,55.5,8.500,False,231,"(418.30859375, 195.5715789794922, 433.50662231...",table
20400,9.,9.500,False,231,"(51.08998489379883, 422.1288757324219, 60.4883...",table
20413,FY 25,7.000,False,231,"(451.7909851074219, 580.7269897460938, 467.676...",table
20414,FY 24,7.000,False,231,"(523.81396484375, 580.7269897460938, 539.67742...",table
20417,"1,994",8.500,False,231,"(447.9736022949219, 609.281494140625, 467.6809...",table
20418,"1,959 $",7.225,False,231,"(517.257080078125, 609.0653686523438, 539.6766...",table
20420,137,8.500,False,231,"(452.8355712890625, 624.2789916992188, 469.597...",table
20421,76,8.500,False,231,"(531.1630859375, 624.2789916992188, 539.680114...",table
20423,2.8,8.500,False,231,"(454.81610107421875, 639.281494140625, 469.595...",table
20424,1.98,8.500,False,231,"(524.4141235351562, 639.281494140625, 539.6775...",table
20426,"6,244",8.500,False,231,"(447.88861083984375, 654.2839965820312, 467.67...",table
20427,"3,180",8.500,False,231,"(520.172607421875, 654.2839965820312, 539.6776...",table
20429,202,8.500,False,231,"(452.8186340332031, 669.2864990234375, 469.595...",table
20430,233,8.500,False,231,"(526.6326293945312, 669.2864990234375, 539.673...",table
20435,"3,934",8.500,False,231,"(448.0926208496094, 699.29150390625, 467.67318...",table
20436,"4,009",8.500,False,231,"(519.7051391601562, 699.29150390625, 539.66906...",table
20439,"90,087*",8.500,False,231,"(439.21014404296875, 714.2940063476562, 467.66...",table
20440,"81,488 $",7.225,False,231,"(512.4546508789062, 714.0653686523438, 539.676...",table
20442,"1,02,601",8.500,False,231,"(435.3935852050781, 741.2792358398438, 467.678...",table
20443,"90,947",8.500,False,231,"(515.7015991210938, 741.2792358398438, 539.677...",table

In [82]:
df_6[(df_6["label"] == 'body') & (df_6["page"] == 231)]

,text,size,is_bold,page,bbox,label
20357,80 th Integrated Annual Report,7.65,False,231,"(61.64540100097656, 789.0324096679688, 164.685...",body
20361,Plant Locations,7.00,False,231,"(74.86609649658203, 112.72699737548828, 120.63...",body
20362,Total Roof Top PV Solar installed capacity til...,7.00,False,231,"(338.05908203125, 112.72699737548828, 513.7518...",body
20363,"Pimpri, Pune",8.50,False,231,"(74.86609649658203, 123.27899932861328, 119.47...",body
20365,"Chinchwad, Pune",8.50,False,231,"(74.8660888671875, 135.281005859375, 135.26879...",body
20367,Jamshedpur,8.50,False,231,"(74.8660888671875, 147.28302001953125, 117.395...",body
20369,Lucknow,8.50,False,231,"(74.8660888671875, 159.2850341796875, 105.9148...",body
20371,Pantnagar,8.50,False,231,"(74.8660888671875, 171.28704833984375, 110.691...",body
20373,Dharwad,8.50,False,231,"(74.8660888671875, 183.2890625, 106.8872833251...",body
20375,Total,8.50,False,231,"(74.8660888671875, 195.5715789794922, 92.06329...",body
20377,Energy Conservation (ENCON) projects are imple...,9.50,False,231,"(70.86910247802734, 215.2530059814453, 546.398...",body
20378,"manner. In FY25, ENCON Projects led to a cumul...",9.50,False,231,"(70.86910247802734, 227.25148010253906, 546.39...",body
20379,amounted to a reduction of 3978 tCO 2 of green...,8.55,False,231,"(70.86910247802734, 239.2499542236328, 538.000...",body
20381,Optimization of compressed air consumption at ...,9.50,False,231,"(90.71249389648438, 254.2534942626953, 546.395...",body
20382,CO 2 emissions.,8.55,False,231,"(90.71249389648438, 266.251953125, 148.1325073...",body
20384,Elimination of the Sealer Oven process in the ...,9.50,False,231,"(90.71449279785156, 281.25347900390625, 481.18...",body
20386,Implementation of Variable Refrigerant Flow (V...,9.50,False,231,"(90.72399139404297, 296.25396728515625, 546.41...",body
20387,energy efficiency.,9.50,False,231,"(90.72399139404297, 308.25244140625, 160.07868...",body
20389,Achievement of energy savings through Foundry ...,9.50,False,231,"(90.73348999023438, 323.2529296875, 546.431152...",body
20390,"improvement across various items, contributing...",9.50,False,231,"(90.73348999023438, 335.2514343261719, 426.121...",body
20392,Eliminated sealer baking process on paint shop...,9.50,False,231,"(90.74298858642578, 350.2519226074219, 546.429...",body
20393,propane consumption.,9.50,False,231,"(90.74298858642578, 362.25042724609375, 179.22...",body
20395,Heat Pump utilization for Paint shop Process t...,9.50,False,231,"(90.75248718261719, 377.25091552734375, 316.12...",body
20397,Digitization and furnace optimization in heat ...,9.50,False,231,"(90.7619857788086, 392.25140380859375, 327.335...",body
20399,Energy efficient HVLS fans installation at var...,9.50,False,231,"(90.771484375, 407.25189208984375, 340.0696716...",body
20401,Provide details related to waste management by...,9.50,False,231,"(70.93548583984375, 422.1288757324219, 309.001...",body
20402,The waste generated from our operations compri...,9.50,False,231,"(70.93548583984375, 437.25286865234375, 546.47...",body
20403,along with scrap material. Our waste managemen...,9.50,False,231,"(70.93548583984375, 449.2513732910156, 546.474...",body
20404,by the respective State Pollution Control Boar...,9.50,False,231,"(70.93548583984375, 461.2498779296875, 546.466...",body
20405,"at eliminating, minimizing, and recycling wast...",9.50,False,231,"(70.93548583984375, 473.2483825683594, 546.458...",body
20406,"initiatives encompass various activities, incl...",9.50,False,231,"(70.93548583984375, 485.24688720703125, 546.47...",body
20407,"oil, solvents, paint sludge, and used foundry ...",9.50,False,231,"(70.93548583984375, 497.2453918457031, 546.470...",body
20408,hazardous waste as alternate fuel and raw mate...,9.50,False,231,"(70.93548583984375, 509.243896484375, 546.4756...",body
20409,"oily rags, and composting of food waste. Furth...",9.50,False,231,"(70.93548583984375, 521.2423706054688, 546.464...",body
20410,authorized recyclers.,9.50,False,231,"(70.93548583984375, 533.2409057617188, 152.501...",body
20411,"Furthermore, we are committed to achieving Zer...",9.50,False,231,"(70.93548583984375, 548.2413940429688, 546.464...",body
20412,are carrying this message across our value cha...,9.50,False,231,"(70.93548583984375, 560.2399291992188, 422.316...",body
20415,Total waste generated (in metric tonnes),8.50,False,231,"(74.86609649658203, 594.1685180664062, 220.841...",body
20416,Plastic waste (A),8.50,False,231,"(74.86609649658203, 609.281494140625, 132.1884...",body
20419,E-waste (B),8.50,False,231,"(74.86609649658203, 624.2789916992188, 114.022...",body
20422,Bio-medical waste (C),8.50,False,231,"(74.8660888671875, 639.281494140625, 151.01930...",body
20425,Construction and demolition waste (D),8.50,False,231,"(74.86611938476562, 654.2839965820312, 210.673...",body
20428,Battery waste (E),8.50,False,231,"(74.86611938476562, 669.2864990234375, 135.068...",body
20431,Radioactive waste (F),8.50,False,231,"(74.86614990234375, 684.2890014648438, 149.595...",body
20434,"Other hazardous waste. Please specify, if any....",8.50,False,231,"(74.86611938476562, 699.29150390625, 246.44120...",body
20437,Other non-hazardous waste generated (H). Pleas...,8.50,False,231,"(74.85763549804688, 714.2940063476562, 397.582...",body
20438,i.e. by materials relevant to the sector),8.50,False,231,"(74.85763549804688, 726.2960205078125, 210.613...",body
20441,Total (A+B + C + D + E + F + G + H),8.50,False,231,"(74.86609649658203, 741.1687622070312, 191.335...",body

## Observations: We got the table numbers on the 'table' label and row names on the 'body' label, now we will merge it using bbox's y value

In [83]:
all_lines.sort(key=lambda x: (x["page"], x["bbox"][1]))

In [85]:
## LEt's start by grouping lines by Y

def group_rows(lines, y_tol = 3):
    rows = []
    current_row = []

    for line in lines:
        if not current_row:
            current_row.append(line)
            continue

        prev_y = current_row[-1]["bbox"][1]
        curr_y = line["bbox"][1]

        if abs(curr_y - prev_y) < y_tol:
            current_row.append(line)
        else:
            rows.append(current_row)
            current_row = [line]
    
    if current_row:
        rows.append(current_row)

    return rows

In [86]:
## Detect table rows
def is_table_row(row):
    texts = [l["text"] for l in row]

    numeric_parts = sum(1 for t in texts if numeric_ratio(t) > 0.4)

    return numeric_parts >= 1

In [87]:
## Merging a row meaningfully
def row_to_text(row):
    texts = [l["text"] for l in row]

    if len(texts) == 1:
        return texts[0]
    
    return f"{texts[0]}: " + ", ".join(texts[1:])

In [91]:
## Now let's group rows in tables
def group_tables(rows):
    tables = []
    current_table = []

    for row in rows:
        if is_table_row(row):
            current_table.append(row)
        else:
            if current_table:
                tables.append(current_table)
                current_table = []
    
    if current_table:
        tables.append(current_table)
    
    return tables

In [94]:
def table_to_text(table):
    lines = []
    for row in table:
        lines.append(row_to_text(row))
    return "Table Data:\n" + "\n".join(lines)

In [97]:
## So let's implement
grouped_rows = group_rows(all_lines)
rtx_list = []

for row in grouped_rows:
    rtx = row_to_text(row)
    rtx_list.append(rtx)

## Group the tables
tables = group_tables(grouped_rows)

table_texts = [table_to_text(t) for t in tables]
table_texts[2000]

'Table Data:\nAs % of: consolidated, 2.09%, 3.02%, 0.32%, 1.33%, 0.00%, 1.97%, 19.12%, 0.00%, -0.23%, 0.01%, -0.13%, 0.34%, -0.07%, 0.00%, 0.18%, 0.00%, 0.01%, -0.01%, 0.00%, 0.00%, 0.14%, 0.56%, -0.03%, 0.00%, 0.11%, 11.51%, 0.00%, -0.04%, 0.00%, 8.42%, 72.37%, 0.00%, 39.95%, 0.98%, -0.03%, 0.00%, -0.04%, 0.00%, 0.70%, 0.17%, profit or loss\nAmount: 1,664, 5,742, 707, 8,640, 32,041, 141, 765, 4,971, -, 540, 163, (57), (31), 111, 60, -, (69), 41, 25, 319, 2,010, 549, 30, 8,542, (929), 48, 65,092, 7, 3, 65,132, 30,833, 24, 840, 1,172, 1, 78, 57, 1, 779, (₹ in crores), Net Assets, i.e. total assets'